In [1]:
import numpy as np

In [2]:
from logistic_regression import LogisticRegression as MyLogReg

In [3]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, make_scorer

In [4]:
X, y = make_classification(n_samples=1000, n_classes=2, n_informative=14, random_state=43)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
clf = MyLogReg()

In [7]:
clf.fit(X_train, y_train)

In [8]:
roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

0.8495115207373272

! когда используем регуляризацию - нужно приводить признаки к одной шкале

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
clf = LogisticRegression()

In [11]:
clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [12]:
roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

0.8494746543778803

In [13]:
X, y = make_classification(n_samples=50000, n_classes=5, n_informative=14, random_state=43)

In [14]:
from sklearn.model_selection import StratifiedKFold

In [15]:
skf = StratifiedKFold(n_splits=2)

In [16]:
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [24654 24666 24676 ... 49997 49998 49999] TEST: [    0     1     2 ... 25367 25370 25372]
TRAIN: [    0     1     2 ... 25367 25370 25372] TEST: [24654 24666 24676 ... 49997 49998 49999]


In [17]:
X_train

array([[ 0.72577863,  4.09337819, -0.34064568, ..., -0.33740688,
         4.98049822,  1.32503991],
       [-3.24806159, -3.29490402,  1.0273469 , ...,  1.09612675,
         0.6021073 ,  0.09053431],
       [-1.39035466, -4.29343499, -0.65759843, ..., -0.10978733,
         3.01123305, -0.16324582],
       ...,
       [ 0.66109746,  4.71870507,  0.46897452, ...,  1.11098671,
        -0.80903476, -0.68851757],
       [ 3.16762649,  0.57316206,  0.55641102, ..., -0.12700378,
        -8.079823  , -3.00626495],
       [ 3.0680205 , -4.01426127,  1.7927684 , ..., -0.46072578,
         2.33751353,  1.65614635]])

In [18]:
y_train

array([2, 0, 0, ..., 0, 0, 0])

In [19]:
y_test

array([2, 2, 2, ..., 4, 3, 3])

In [24]:
clf = MyLogReg(lambda_coef=0.1, regularization="L1", alpha=0.1)
clf.fit(X_train, y_train)

In [25]:
predictions = clf.predict(X_test)
predictions

array([2, 0, 2, ..., 4, 3, 3], dtype=int64)

In [26]:
y_test

array([2, 2, 2, ..., 4, 3, 3])

In [27]:
print("Training accuracy:", str(100 * np.mean(predictions == y_test)) + "%")

Training accuracy: 53.79015160606424%
