In [1]:
import numpy as np

In [1]:
from logistic_regression import LogisticRegression as MyLogReg

In [2]:
import metrics

In [3]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, make_scorer, log_loss, precision_score, accuracy_score, recall_score

In [4]:
X, y = make_classification(n_samples=1000, n_classes=2, n_informative=14, random_state=43)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
clf = MyLogReg(n_iter=100000, lambda_coef = 0.001, regulatization = 'L1')

In [9]:
clf.fit(X_train, y_train)

In [10]:
clf.coef_

array([ 0.00175038,  0.00840307,  0.06492644,  0.08901498, -0.04878582,
        0.01233251, -0.01228322,  0.01401457, -0.07928461,  0.01569487,
       -0.00162964, -0.07943833,  0.00174679, -0.02414639,  0.0472893 ,
       -0.15973679, -0.06492155,  0.07173327,  0.00535737, -0.06984794])

In [11]:
metrics.roc_auc(y_test, clf.predict_proba(X_test))

0.8294009216589862

In [12]:
metrics.logloss(y_test, clf.predict_proba(X_test))

0.5795657516501859

In [13]:
metrics.accuracy(y_test, clf.predict(X_test))

0.6727272727272727

In [14]:
metrics.presicion(y_test, clf.predict(X_test))

0.6008583690987125

In [15]:
metrics.recall(y_test, clf.predict(X_test))

0.9032258064516129

In [16]:
clf.get_weights()

array([ 0.01091002,  0.00175038,  0.00840307,  0.06492644,  0.08901498,
       -0.04878582,  0.01233251, -0.01228322,  0.01401457, -0.07928461,
        0.01569487, -0.00162964, -0.07943833,  0.00174679, -0.02414639,
        0.0472893 , -0.15973679, -0.06492155,  0.07173327,  0.00535737,
       -0.06984794])

Что получится, используя sklearn

In [15]:
from sklearn.linear_model import LogisticRegression

In [33]:
clf = LogisticRegression()

In [34]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
roc_auc_score(y_test, clf.predict_proba(X_test))

0.8293824884792628

In [18]:
clf.coef_

array([ 0.00175038,  0.00840307,  0.06492644,  0.08901498, -0.04878582,
        0.01233251, -0.01228322,  0.01401457, -0.07928461,  0.01569487,
       -0.00162964, -0.07943833,  0.00174679, -0.02414639,  0.0472893 ,
       -0.15973679, -0.06492155,  0.07173327,  0.00535737, -0.06984794])

In [19]:
clf.intercept_

0.010910023399265726

In [20]:
log_loss(y_test, clf.predict_proba(X_test))

0.5795657516501859

In [21]:
roc_auc_score(y_test, clf.predict_proba(X_test))

0.8293824884792628

In [22]:
precision_score(y_test, clf.predict(X_test))

0.6008583690987125

In [23]:
recall_score(y_test, clf.predict(X_test))

0.9032258064516129

In [24]:
accuracy_score(y_test, clf.predict(X_test))

0.6727272727272727