In [1]:
import numpy as np

In [2]:
from logistic_regression import LogisticRegression as MyLogReg

In [3]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, make_scorer

In [4]:
X, y = make_classification(n_samples=1000, n_classes=2, n_informative=14, random_state=43)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
clf = MyLogReg()

In [7]:
clf.fit(X_train, y_train)

In [8]:
roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

0.8495115207373272

! когда используем регуляризацию - нужно приводить признаки к одной шкале

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
clf = LogisticRegression()

In [11]:
clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [12]:
roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])

0.8494746543778803

In [59]:
X, y = make_classification(n_samples=30000, n_classes=5, n_informative=14, random_state=43)

In [60]:
from sklearn.model_selection import StratifiedKFold

In [61]:
skf = StratifiedKFold(n_splits=2)

In [62]:
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [14661 14662 14674 ... 29997 29998 29999] TEST: [    0     1     2 ... 15251 15274 15275]
TRAIN: [    0     1     2 ... 15251 15274 15275] TEST: [14661 14662 14674 ... 29997 29998 29999]


In [63]:
X_train

array([[ 0.28199781, -6.34890577, -3.039408  , ..., -0.70172213,
        -4.70522007, -5.24459525],
       [-0.76648564, -0.65870285,  5.55211911, ..., -5.59207335,
        -0.82648512,  3.40028109],
       [ 2.77406608,  0.85394962, -2.6930368 , ..., -2.48028273,
         0.85252464, -4.67103891],
       ...,
       [-0.38864836,  1.91685897, -3.34719294, ..., -0.20597523,
        -0.54271433, -1.90881037],
       [-0.15216177,  3.87270271, -2.5793541 , ...,  1.62080366,
         1.99818715,  2.79093006],
       [-8.09050007,  1.55378002, -3.52132818, ...,  1.26905992,
         0.55718983,  4.07336104]])

In [64]:
y_train

array([1, 0, 0, ..., 0, 4, 4])

In [65]:
y_test

array([2, 2, 2, ..., 3, 2, 1])

In [66]:
clf = MyLogReg(lambda_coef=0.1, regularization=None, alpha=0.5)
clf.fit(X_train, y_train)

In [67]:
predictions = clf.predict(X_test)
predictions

array([4, 2, 2, ..., 1, 2, 1], dtype=int64)

In [68]:
y_test

array([2, 2, 2, ..., 3, 2, 1])

In [69]:
print("Training accuracy:", str(100 * np.mean(predictions == y_test)) + "%")

Training accuracy: 53.260434724629945%
