# `numpy`

In [2]:
import numpy as np

## Как создать массив в `numpy`?

In [3]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float128)

AttributeError: module 'numpy' has no attribute 'float128'

In [4]:
a

array(['1', '2', '汉'], dtype='<U1')

In [5]:
b

array([1, 2, 3], dtype=uint16)

In [6]:
c

NameError: name 'c' is not defined

In [7]:
print(c.shape)

NameError: name 'c' is not defined

In [8]:
print(c.dtype)

NameError: name 'c' is not defined

### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [9]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [11]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [12]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[ -5, -10,  -2,  -8,   2],
       [ -2,  -9,  -6,   0,  -2]])

## Индексирование и слайсы

In [14]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[66 41 51 79  0 95 17 63  9 81]
 [99 47 81 32 80 38 49 56 83 12]
 [50 90 21 54 25 97 18 19 52 15]
 [ 9 82 42 39 64 58 52 98 60 71]
 [33  9 98 41 24 74 64 61 74 59]]


In [15]:
a[0]

array([66, 41, 51, 79,  0, 95, 17, 63,  9, 81])

In [16]:
a[0, 1] # the same as a[0][1]

41

In [17]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([41, 47, 90, 82,  9])

In [18]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([ 9, 83, 52, 60])

In [19]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([33, 98, 24, 64, 74])

In [20]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([ 9, 41, 74, 61, 59])

In [21]:
# все положительные элементы массива: любое условие написать можно
a[a > 0]

array([66, 41, 51, 79, 95, 17, 63,  9, 81, 99, 47, 81, 32, 80, 38, 49, 56,
       83, 12, 50, 90, 21, 54, 25, 97, 18, 19, 52, 15,  9, 82, 42, 39, 64,
       58, 52, 98, 60, 71, 33,  9, 98, 41, 24, 74, 64, 61, 74, 59])

In [22]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[66, 41, 51, 79,  0, 95, 17, 63,  9, 81],
       [33,  9, 98, 41, 24, 74, 64, 61, 74, 59]])

### Для присваивания тоже работает!

In [23]:
a

array([[66, 41, 51, 79,  0, 95, 17, 63,  9, 81],
       [99, 47, 81, 32, 80, 38, 49, 56, 83, 12],
       [50, 90, 21, 54, 25, 97, 18, 19, 52, 15],
       [ 9, 82, 42, 39, 64, 58, 52, 98, 60, 71],
       [33,  9, 98, 41, 24, 74, 64, 61, 74, 59]])

In [24]:
a[1:-1, :] = 1
a

array([[66, 41, 51, 79,  0, 95, 17, 63,  9, 81],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [33,  9, 98, 41, 24, 74, 64, 61, 74, 59]])

In [25]:
a[:, 1:3] = np.arange(2) #все строки,с 1 го по 3 не включ
a

array([[66,  0,  1, 79,  0, 95, 17, 63,  9, 81],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [33,  0,  1, 41, 24, 74, 64, 61, 74, 59]])

## Операции с `np.array`

In [26]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[16 78 73 55]
 [76 77 53 40]
 [19 46 72 32]]

b: [[35 88 70 29]
 [40 97 37 59]
 [ 4 62 82 57]]

c: [89 69 38 55]



In [27]:
print(a.reshape((2, 6))) # the same as a.shape = (1, 6)

[[16 78 73 55 76 77]
 [53 40 19 46 72 32]]


In [28]:
print(a.T)

[[16 76 19]
 [78 77 46]
 [73 53 72]
 [55 40 32]]


In [29]:
a + b

array([[ 51, 166, 143,  84],
       [116, 174,  90,  99],
       [ 23, 108, 154,  89]])

In [30]:
a - b

array([[-19, -10,   3,  26],
       [ 36, -20,  16, -19],
       [ 15, -16, -10, -25]])

In [31]:
# какое это умножение? поэдементное 
a * b

array([[ 560, 6864, 5110, 1595],
       [3040, 7469, 1961, 2360],
       [  76, 2852, 5904, 1824]])

In [32]:
# а это? умножение матриц,главное транспануть
a @ b.T

array([[14129, 14152, 14021],
       [14306, 14830, 11704],
       [10681,  9774, 10656]])

In [33]:
a / b #поэлемнетное

array([[0.45714286, 0.88636364, 1.04285714, 1.89655172],
       [1.9       , 0.79381443, 1.43243243, 0.6779661 ],
       [4.75      , 0.74193548, 0.87804878, 0.56140351]])

In [34]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]], dtype=int32)

In [35]:
np.sqrt(b)

array([[5.91607978, 9.38083152, 8.36660027, 5.38516481],
       [6.32455532, 9.8488578 , 6.08276253, 7.68114575],
       [2.        , 7.87400787, 9.05538514, 7.54983444]])

In [36]:
np.sum(b)

660

In [38]:
np.sum(b, axis=0)#сумма по колонкам

array([ 79, 247, 189, 145])

In [39]:
np.min(a[0])

4

In [40]:
np.vstack([a, b])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [41]:
np.hstack([a, b])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

### Волшебный `np.vectorize`

In [42]:
pow_2 = lambda x: x ** 2

In [43]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16], dtype=int32)

In [44]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [46]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [48]:
d

42

In [49]:
a


array([[5, 4],
       [7, 8]])

In [50]:
a + d

array([[47, 46],
       [49, 50]])

In [51]:
c


array([89, 69, 38, 55])

In [53]:
c + a

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [54]:
b - d

array([[ -7,  46,  28, -13],
       [ -2,  55,  -5,  17],
       [-38,  20,  40,  15]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [55]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

2009981


### Задание: написать решалку линейных уравнений

In [64]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    C=linalg.inv(A)@y
    
    return C


### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [57]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    return

## Few more things:

### `np.random.seed()`

In [60]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.seed(2)
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 4 1 3 0]
[2 4 1 3 0]
[2 4 1 3 0]
[2 4 1 3 0]
[2 4 1 3 0]


In [61]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [65]:
np.float128(1 / 3) * 3 == 1

AttributeError: module 'numpy' has no attribute 'float128'

In [66]:
np.isclose(np.float128(1 / 3) * 3, 1)

AttributeError: module 'numpy' has no attribute 'float128'

---

# scipy.sparse

In [67]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [68]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

4000112
56


In [69]:
a.mean()

0.499759

#### Или можно вот так вот создать:

In [70]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 2, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  9,  0,  0],
       [10,  0,  0,  0,  0]], dtype=int32)